DATASET:
  DATASET: 'ade20k'
  DATA_PATH: '../dataset'

TRAINING:
  NUM_THREADS: 16
  BATCH_SIZE: 32
  BATCH_SIZE_ON_1_GPU: 8
  NUM_EPOCHS: 50
  MAX_LR: 1e-4
  EVAL_FREQ: 1

MODEL:
  MODEL_TYPE: 'upernet'
  BINARY_TYPE: 'fp32_0'
  NUM_CLASSES: 151
