from .upernet import UperNetDepthModel, UperNetSegmentationModel
from .bnn_upernet import BnnUperNetDepthModel, BnnUperNetSegmentationModel
from .react_upernet import ReActUperNetDepthModel, ReActUperNetSegmentationModel
