from .upernet import UperNetDepthModel, UperNetSegmentationModel
from .bnn_upernet import BnnUperNetDepthModel, BnnUperNetSegmentationModel
from .react_upernet import ReActUperNetDepthModel, ReActUperNetSegmentationModel
from .adabin_upernet import AdaBinUperNetDepthModel, AdaBinUperNetSegmentationModel
from .bisrnet_upernet import BiSRUperNetDepthModel, BiSRUperNetSegmentationModel
from .cfb_upernet import CFBUperNetDepthModel, CFBUperNetSegmentationModel
from .bidense_upernet import BiDenseUperNetDepthModel, BiDenseUperNetSegmentationModel
