DATASET:
  DATASET: 'kitti'
  DATA_PATH: '../dataset/kitti_dataset/'
  GT_PATH: '../dataset/kitti_dataset/data_depth_annotated/'
  FILENAMES_FILE: 'train_test_inputs/eigen_train_files_with_gt.txt'
  DATA_PATH_EVAL: '../dataset/kitti_dataset/'
  GT_PATH_EVAL: '../dataset/kitti_dataset/data_depth_annotated/'
  FILENAMES_FILE_EVAL: 'train_test_inputs/eigen_test_files_with_gt.txt'

  INPUT_HEIGHT: 352
  INPUT_WIDTH: 704

PREPROCESSING:
  DO_KB_CROP: True
  DO_RANDOM_ROTATE: True
  DEGREE: 1.0

TRAINING:
  NUM_THREADS: 16
  BATCH_SIZE: 32
  BATCH_SIZE_ON_1_GPU: 4
  NUM_EPOCHS: 50
  MAX_LR: 3e-5

ONLINE_EVAL:
  MIN_DEPTH_EVAL: 1e-3
  MAX_DEPTH_EVAL: 80
  GARG_CROP: True
  EIGEN_CROP: False

MODEL:
  MODEL_TYPE: 'dpt'
  BINARY_TYPE: 'bivit'
  MAX_DEPTH: 80